import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { detectFramework, detectDatabase, detectPackageManager } from '../core/detect.js';
import { header, success, warn, info, c } from '../core/output.js';
import type { Framework } from '../types.js';

// Default port ranges by framework type
const PORT_RANGES: Record<string, number> = {
  nextjs: 3000,
  sveltekit: 3020,
  vite: 3040,
  vue: 3060,
  django: 8000,
};

interface ScannedProject {
  slug: string;
  path: string;
  framework: Framework | null;
  hasDatabase: boolean;
  packageManager: string | null;
  suggestedPort: number;
}

export function commandInit(args: string[]): void {
  const workspaceRoot = resolve(args[0] || '.');
  const tomlPath = join(workspaceRoot, 'starto.toml');

  if (existsSync(tomlPath)) {
    warn(`starto.toml already exists at ${tomlPath}`);
    warn('Delete it first if you want to regenerate.');
    process.exit(1);
  }

  header('starto init');
  info(`Scanning ${workspaceRoot} for projects...\n`);

  // Scan for directories with package.json
  const entries = readdirSync(workspaceRoot, { withFileTypes: true });
  const projects: ScannedProject[] = [];
  const usedPorts = new Set<number>();

  // Track next available port per framework type
  const nextPort: Record<string, number> = { ...PORT_RANGES };

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('.') || entry.name.startsWith('_')) continue;

    const dirPath = join(workspaceRoot, entry.name);
    const pkgPath = join(dirPath, 'package.json');

    if (!existsSync(pkgPath)) continue;

    const framework = detectFramework(dirPath);
    const hasDatabase = detectDatabase(dirPath);
    const packageManager = detectPackageManager(dirPath);

    // Assign port based on framework type
    const portBase = framework ? (nextPort[framework] || 3000) : 3000;
    let port = portBase;
    while (usedPorts.has(port)) port++;
    usedPorts.add(port);
    if (framework && nextPort[framework] !== undefined) {
      nextPort[framework] = port + 1;
    }

    projects.push({
      slug: entry.name,
      path: dirPath,
      framework,
      hasDatabase,
      packageManager,
      suggestedPort: port,
    });
  }

  if (projects.length === 0) {
    warn('No projects found (no directories with package.json).');
    process.exit(0);
  }

  // Display what we found
  for (const p of projects) {
    const fw = p.framework ? c('cyan', p.framework) : c('dim', 'unknown');
    const db = p.hasDatabase ? c('yellow', ' +db') : '';
    info(`${c('bold', p.slug.padEnd(28))} ${fw.padEnd(22)} → port ${c('green', String(p.suggestedPort))}${db}`);
  }

  console.log();
  info(`Found ${c('bold', String(projects.length))} projects.\n`);

  // Generate starto.toml
  let toml = `# starto.toml — project registry\n# Generated by starto init\n\n`;
  toml += `[workspace]\nroot = "."\n\n`;

  // Port ranges documentation
  toml += `# [ports]\n# range = [3000, 3099]\n\n`;

  for (const p of projects) {
    toml += `[projects.${p.slug}]\n`;
    toml += `port = ${p.suggestedPort}\n`;
    if (p.framework) {
      toml += `# framework = "${p.framework}"  # auto-detected\n`;
    }
    if (p.hasDatabase) {
      toml += `database = true\n`;
      toml += `# setup = "npx prisma migrate deploy"\n`;
    }
    toml += `\n`;
  }

  writeFileSync(tomlPath, toml);
  success(`Created ${tomlPath}`);
  info(`Edit it to adjust ports, add setup commands, or enable databases.`);
  info(`Then run ${c('cyan', 'starto list')} to see your workspace.`);
}
